stages:
  load_data:
    cmd: python src/load_n_save.py --config=config/config.yaml
    deps:
      - src/load_n_save.py
      - src/utils/all_utils.py
      - config/config.yaml
      - data_given/bending1
      - data_given/bending2
      - data_given/cycling/
      - data_given/lying
      - data_given/sitting
      - data_given/standing
      - data_given/walking
    outs:
      - data/raw/final_data.csv
  preprocess_data:
    cmd: python src/EDA_and_Preprocessing.py --config=config/config.yaml
    deps:
      - src/EDA_and_Preprocessing.py
      - src/utils/all_utils.py
      - config/config.yaml
      - data/raw/final_data.csv
    outs:
      - data/EDA_report/profiling_report.html
      - data/preprocess_data/preprocess_Data.csv
  scaling_n_spilliting_data:
    cmd: python src/scaling_n_splitting.py --config=config/config.yaml --params=params.yaml
    deps:
      - src/scaling_n_splitting.py
      - src/utils/all_utils.py
      - config/config.yaml
      - params.yaml
      - data/preprocess_data/preprocess_Data.csv
    params:
      - base.test_size
      - base.random_state
    outs:
      - models/Standardized_model/StandardScalar_model.sav
      - data/splitted_data/x_train.csv
      - data/splitted_data/x_test.csv
      - data/splitted_data/y_train.csv
      - data/splitted_data/y_test.csv
  train:
    cmd: python src/train_model.py --config=config/config.yaml --params=params.yaml
    deps:
      - src/train_model.py
      - src/utils/all_utils.py
      - config/config.yaml
      - params.yaml
      - data/splitted_data/x_train.csv
      - data/splitted_data/y_train.csv
    params:
      - Logistic_model_params.multi_class
      - Logistic_model_params.solver
      - Logistic_model_params.random_state
    outs:
      - models/Trained_model/Logistic_model.sav
  evaluate:
    cmd: python src/evaluate.py --config=config/config.yaml
    deps:
      - src/evaluate.py
      - src/utils/all_utils.py
      - config/config.yaml
      - data/splitted_data/x_test.csv
      - data/splitted_data/y_test.csv
      - models/Trained_model/Logistic_model.sav
    outs:
      - data/evaluation_metrics/scores.json