
data_source:
  s3_source: data_given

data:
  data_dir: data
  raw_local_dir: raw
  raw_local_file: final_data.csv

  EDA_report_dir: EDA_report
  EDA_file: profiling_report.html

  preprocess_data_dir: preprocess_data
  preprocess_data_file: preprocess_Data.csv

  splitted_data_dir: splitted_data
  x_train_data_file: x_train.csv
  x_test_data_file: x_test.csv
  y_train_data_file: y_train.csv
  y_test_data_file: y_test.csv


models:
  model_dir: models
  scaled_model: Standardized_model  # here name should be <scaled_model_dir> instead of <scaled_model>
  scaled_model_file: StandardScalar_model.sav

  trained_model_dir: Trained_model
  trained_model_file: Logistic_model.sav

logs:
  log_dir: logg
  log_file: logging.log