
data_source:
  s3_source: data_given

data:
  data_dir: data
  raw_local_dir: raw
  raw_local_file: final_data.csv
  EDA_report_dir: EDA_report
  EDA_file: profiling_report.html
  preprocess_data_dir: preprocess_data
  preprocess_data_file: preprocess_Data.csv

logs:
  log_dir: logg
  log_file: logging.log